# Generated by Django 3.2.3 on 2024-09-26 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240926_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='amount',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinValueValidator(1, message='Колличество ингредиента не может быть меньше 1')], verbose_name='Колличество'),
        ),
    ]
