# Generated by Django 3.2.3 on 2024-09-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240926_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipe',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
