# Generated by Django 3.2.3 on 2024-10-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20241004_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='api.IngredientsRecipe', to='api.Ingredients', verbose_name='Ингредиенты'),
        ),
    ]
