# Generated by Django 3.2.3 on 2024-10-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='api.TagsRecipe', to='api.Tags', verbose_name='Теги'),
        ),
    ]
